import type { Metadata } from "next";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignOutButton,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hasClerkPublishableKey = Boolean(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {hasClerkPublishableKey ? (
          <ClerkProvider
            appearance={{
              elements: {
                // Solid purple avatar (no gradient) for the user button.
                userButtonAvatarBox: "bg-purple-600",
              },
            }}
          >
            <header className="border-b">
              <div className="mx-auto flex max-w-4xl items-center justify-between p-4">
                <Link href="/" className="text-lg font-semibold leading-none">
                  QuotaShield
                </Link>
                <div className="flex items-center gap-3">
                  <SignedOut>
                    <SignInButton>
                      <button className="text-sm">Sign in</button>
                    </SignInButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                    <SignOutButton>
                      <button className="text-sm">Sign out</button>
                    </SignOutButton>
                  </SignedIn>
                </div>
              </div>
            </header>
            {children}
          </ClerkProvider>
        ) : (
          <>
            <header className="border-b">
              <div className="mx-auto flex max-w-4xl items-center justify-between p-4">
                <Link href="/" className="text-lg font-semibold leading-none">
                  QuotaShield
                </Link>
                <div className="text-xs text-gray-600">
                  Clerk not configured (set env vars in <code>.env.local</code>)
                </div>
              </div>
            </header>
            {children}
          </>
        )}
      </body>
    </html>
  );
}
